version: 0.2
env:
  variables:
    GOOS: "linux"
phases:
  build:
    commands:
      - go test
      - go build -o main
  post_build:
    commands:
      - zip build.zip main
artifacts:
  files:
    - build.zip
